// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Check struct {
	ID         string
	ServiceID  string
	ProjectID  string
	CheckedAt  string
	Status     string
	StatusCode int64
	LatencyMs  int64
	Error      string
}

type Project struct {
	ID          string
	WorkspaceID string
	Name        string
	Slug        string
	CreatedAt   string
}

type Service struct {
	ID               string
	ProjectID        string
	Name             string
	Slug             string
	Type             string
	Url              string
	Hostname         string
	Port             int64
	IntervalSeconds  int64
	TimeoutSeconds   int64
	FailureThreshold int64
	Enabled          int64
	NextRunAt        sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

type ServiceState struct {
	ServiceID            string
	ProjectID            string
	State                string
	ConsecutiveFailures  int64
	ConsecutiveSuccesses int64
	LastChangeAt         string
	LastCheckAt          sql.NullString
}

type Session struct {
	ID        string
	UserID    string
	TokenHash string
	CsrfToken string
	ExpiresAt string
	CreatedAt string
}

type UptimeRollup struct {
	ServiceID   string
	ProjectID   string
	Hour        string
	UpChecks    int64
	TotalChecks int64
}

type User struct {
	ID          string
	WorkspaceID string
	Email       string
	Name        string
	Role        string
	GoogleSub   sql.NullString
	Disabled    int64
	CreatedAt   string
	LastLoginAt sql.NullString
}

type Workspace struct {
	ID        string
	Name      string
	Slug      string
	CreatedAt string
}
