// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Project struct {
	ID          string
	WorkspaceID string
	Name        string
	Slug        string
	CreatedAt   string
}

type Service struct {
	ID               string
	ProjectID        string
	Name             string
	Slug             string
	Type             string
	Url              string
	Hostname         string
	Port             int64
	IntervalSeconds  int64
	TimeoutSeconds   int64
	FailureThreshold int64
	Enabled          int64
	CreatedAt        string
	UpdatedAt        string
}

type User struct {
	ID          string
	WorkspaceID string
	Email       string
	Name        string
	Role        string
	GoogleSub   sql.NullString
	Disabled    int64
	CreatedAt   string
	LastLoginAt sql.NullString
}

type Workspace struct {
	ID        string
	Name      string
	Slug      string
	CreatedAt string
}
