// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
)

const countWorkspaces = `-- name: CountWorkspaces :one
SELECT COUNT(*) FROM workspace
`

func (q *Queries) CountWorkspaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkspaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, workspace_id, name, slug, created_at)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type CreateProjectParams struct {
	ID          string
	WorkspaceID string
	Name        string
	Slug        string
	CreatedAt   string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
	)
	return err
}

const createService = `-- name: CreateService :exec
INSERT INTO services (
    id, project_id, name, slug, type, url, hostname, port,
    interval_seconds, timeout_seconds, failure_threshold, enabled,
    created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8,
    ?9, ?10,
    ?11, ?12,
    ?13, ?14
)
`

type CreateServiceParams struct {
	ID               string
	ProjectID        string
	Name             string
	Slug             string
	Type             string
	Url              string
	Hostname         string
	Port             int64
	IntervalSeconds  int64
	TimeoutSeconds   int64
	FailureThreshold int64
	Enabled          int64
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) error {
	_, err := q.db.ExecContext(ctx, createService,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Slug,
		arg.Type,
		arg.Url,
		arg.Hostname,
		arg.Port,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
		arg.FailureThreshold,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO workspace (id, name, slug, created_at)
VALUES (?1, ?2, ?3, ?4)
`

type CreateWorkspaceParams struct {
	ID        string
	Name      string
	Slug      string
	CreatedAt string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
	)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?1
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = ?1
`

func (q *Queries) DeleteService(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteService, id)
	return err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, workspace_id, name, slug, created_at
FROM projects WHERE slug = ?1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getServiceBySlug = `-- name: GetServiceBySlug :one
SELECT id, project_id, name, slug, type, url, hostname, port, interval_seconds, timeout_seconds, failure_threshold, enabled, created_at, updated_at FROM services
WHERE project_id = ?1 AND slug = ?2
`

type GetServiceBySlugParams struct {
	ProjectID string
	Slug      string
}

func (q *Queries) GetServiceBySlug(ctx context.Context, arg GetServiceBySlugParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, getServiceBySlug, arg.ProjectID, arg.Slug)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Url,
		&i.Hostname,
		&i.Port,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.FailureThreshold,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, slug, created_at FROM workspace LIMIT 1
`

func (q *Queries) GetWorkspace(ctx context.Context) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, workspace_id, name, slug, created_at FROM projects ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT id, project_id, name, slug, type, url, hostname, port, interval_seconds, timeout_seconds, failure_threshold, enabled, created_at, updated_at FROM services WHERE project_id = ?1 ORDER BY name
`

func (q *Queries) ListServices(ctx context.Context, projectID string) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServices, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.Url,
			&i.Hostname,
			&i.Port,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.FailureThreshold,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameProject = `-- name: RenameProject :exec
UPDATE projects SET name = ?1 WHERE id = ?2
`

type RenameProjectParams struct {
	Name string
	ID   string
}

func (q *Queries) RenameProject(ctx context.Context, arg RenameProjectParams) error {
	_, err := q.db.ExecContext(ctx, renameProject, arg.Name, arg.ID)
	return err
}

const setServiceEnabled = `-- name: SetServiceEnabled :exec
UPDATE services SET enabled = ?1, updated_at = ?2
WHERE id = ?3
`

type SetServiceEnabledParams struct {
	Enabled   int64
	UpdatedAt string
	ID        string
}

func (q *Queries) SetServiceEnabled(ctx context.Context, arg SetServiceEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setServiceEnabled, arg.Enabled, arg.UpdatedAt, arg.ID)
	return err
}

const updateService = `-- name: UpdateService :exec
UPDATE services SET
    name = ?1,
    url = ?2,
    hostname = ?3,
    port = ?4,
    interval_seconds = ?5,
    timeout_seconds = ?6,
    failure_threshold = ?7,
    updated_at = ?8
WHERE id = ?9
`

type UpdateServiceParams struct {
	Name             string
	Url              string
	Hostname         string
	Port             int64
	IntervalSeconds  int64
	TimeoutSeconds   int64
	FailureThreshold int64
	UpdatedAt        string
	ID               string
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) error {
	_, err := q.db.ExecContext(ctx, updateService,
		arg.Name,
		arg.Url,
		arg.Hostname,
		arg.Port,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
		arg.FailureThreshold,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
